### ISSUE TITLE
hláška neplatný tok

### ISSUE THREAD

**Issue by hitman222** [JKubovy/plugin.video.tipsport.elh#1]
Vyhazuje to hlášku Neplatný tok,zkuste obnovit stránku.

**Comment by jagrs** [comment]
Jak to vypadá? Půjde to opravit? Jinak dobrý nápad...

**Comment by JKubovy** [comment]
Při používání Kodi 17+ je třeba povolit doplňky _inputstream-adaptive_ a _inputstream-rtmp_ v záložce _VideoPlayer InputStream_ v _My Addons_, jinak se bude pokaždé ukazovat hláška _neplatný token_.
Pokud se tyto doplňky, případně celá složka naukazuje, je třeba je nainstalovat. U Windows, se musí nainstalovat nová verze a v instalátoru nechat zaškrtnutné tyto dva doplňky a v Linuxu je třeba nainstalovat _kodi-inputstream-adaptive_ a _kodi-inputstream-rtmp_
`apt-get install kodi-inputstream-adaptive kodi-inputstream-rtmp`

**Comment by jagrs** [comment]
Dobrá práce, díky funguje...
