### ISSUE TITLE
Chyba při aktualizaci na verzi 8.0.0

### ISSUE THREAD

**Issue by bedrich-schindler** [JKubovy/plugin.video.tipsport.elh#12]
Na LibreELEC 9.2.6 s Kodi 18.9 při aktualizaci pluginu na verzi 8.0.0 dojde k chybě "Závislost na xbmc.python 3.0.0 nebyla vyřešena".

Stejný problém hlásí i další na fóru: https://www.xbmc-kodi.cz/prispevek-doplnek-tipsport-elh?page=15

**Comment by luki-luki** [comment]
> Na LibreELEC 9.2.6 s Kodi 18.9 při aktualizaci pluginu na verzi 8.0.0 dojde k chybě "Závislost na xbmc.python 3.0.0 nebyla vyřešena".
> 
> Stejný problém hlásí i další na fóru: https://www.xbmc-kodi.cz/prispevek-doplnek-tipsport-elh?page=15

Potvrdzujem, rovnaky problem pri instalacii na AndroidTV(nVidia Shield) aj na Win10.

**Comment by JKubovy** [comment]
Problém byl způsobený špatným zařazením doplňku do repository (nad čím nemám kontrolu). Verze 0.8.0 je určena pro Kodi 19 a novější a vůbec se neměla objevit v repository pro Kodi 18.9. Nyní by již vše mělo být v pořádku u repo.xbmc-kodi.cz, pokud je doplněk dostupný i v jiné repository, tak to o tom nevím.
Aktuální verze pro Kodi 18.9 je 0.7.2
