### ISSUE TITLE
Android - kodi 18.9 Leia - unable to configure

### ISSUE THREAD

**Issue by Mikolasek93** [JKubovy/plugin.video.tipsport.elh#13]
Ahoj,
nelze provést konfiguraci nad tímto doplňkem v Kodi 18.9 na android sticku mi box s od xiaomi nemám žádné možnosti nastavení, píše to jen "nejsou dostupné žádné kategorie."

Step to reproduce: 
před otevřením aplikace jsem dal nastavení které jsem vybral v kontextovém menu při dlouhém podržení OK tlačítka na ovladači.

viz foto:
![image](https://user-images.githubusercontent.com/16031104/104188718-f9fdaf80-5419-11eb-85e8-7da5fd033e9f.png)

Díky moc za případný fix!

**Comment by JKubovy** [comment]
Mohl bys zapnout logování (Nastavení -> Systém -> Protokolování -> Povolit protokolování ladění), znovu spustit nastavení doplňku a zaslat mi soubor kodi.log? Jelikož nevlastním Mi Box S, tak to nemohu vyzkoušet.
Ještě můžeš zkusit doplněk přeinstalovat, jestli nedošlo k nějaké chybě při instalaci.

**Comment by JKubovy** [comment]
Měsíc bez odpovědi ... zavírám
