### ISSUE TITLE
Oktagon

### ISSUE THREAD

**Issue by palik42** [JKubovy/plugin.video.tipsport.elh#14]
Ahoj,
prosim ta mohol by si spravit:
 1. "filter" alebo zalozku priamo len pre oktagon? nakolko je velmi tazke hladat jednotlive zapasy pri vsetkych prenosoch..
 2. pridat "hard" refresh eventu alebo pluginu - stalo sa mi viac krat ze ked skoncil zapas zapol som iny tak tam pisalo ze zapas sa nevysiela v danom case"stream ještě nebyl spuštěn" (na pc prenos bezal) - ked som restartoval cele zariadenie z kodi tak po  restarte uz bol addon schopny pustit dany stream. je tam asi problem s obnovovanim toho"casu" eventu alebo nieco ..(skusil som aj vypnut addon a zapnut ale nepomohlo to k spusteniu streamu - jedina ucinna vec bola restartovat cele zariadenie)

DAKUJEM

**Comment by JKubovy** [comment]
Ahoj,
1) Uvědomuji si, že se hůř orientuje ve složce "All", ale moc jsem se tím nezabýval z toho důvodu, že ne všechny přenosy umí doplněk zobrazit a bral jsem to jenom jako experimentální část. Možná, že do nějaké budoucí aktualizace přidám rozdělení podle sportů a lig.
2) S tímto jsem se už také setkal a je to z toho důvodu, že Kodi v rámci optimalizace ukládá seznamy do cache a často nezavolá kód, který data obnoví. Pokusím se najít nějaké nastavení, jak by šlo říct Kodi, aby toto nedělal nebo aby si to pamatoval jenom omezenou dobu. Mně osobně pomáhá v této situaci vrátit se na začátek a otevřít složku s ligou znova.

**Comment by JKubovy** [comment]
Ve verzi 0.8.4 je přidané nastavení pro zapnutí složkové struktury všech přenosů. Po zapnutí této volby se nejprve zobrazují složky sportů, poté soutěží daného sportu a nakonec samotné přenosy.
