### ISSUE TITLE
Check internet connection error

### ISSUE THREAD

**Issue by brenzaroman** [JKubovy/plugin.video.tipsport.elh#15]
Po spusteni aplikace na matrixu mi vyskoci error check internet connection, ale ostatni addony funguji bez problemu, takze internet urcite funguje bez problemu. Naposledy jsem to zkousel jeste na predesle verzi 18.9. a tam to fungovalo. Jinak preinstalace nepomohla..

**Comment by JKubovy** [comment]
S touto chybou se potýkám už nějakou dobu. Vypadá to, že Tipsport změnil způsob přihlášení a ještě se mi nepovedlo zjistit, jak se přizpůsobit. Zvláštní je, že někdo tvrdí, že mu to funguje nebo dokonce, že na jednom účtu to nefunguje a na jiném ano (verze doplňku je však stejná).

Pokud se mi povede problém odstranit, tak vydám novou verzi.

**Comment by brenzaroman** [comment]
Diky moc za info

Dne pá 2. 7. 2021 9:27 uživatel Jan Kubovy ***@***.***>
napsal:

**Comment by JKubovy** [comment]
V nové verzi 0.8.5 jsem upravil způsob přihlašování. Zjistil jsem, že Tipsport začal používat captcha, když se domnívá, že se jedná o automatizované přihlášení, takže sám nevím, jak stabilně to bude fungovat.

**Comment by JKubovy** [comment]
Uživatelé hlásí, že nová verze (0.8.5 pro Kodi 19+ a 0.7.5 pro Kodi 18) funguje, takže zavírám.
