### ISSUE TITLE
Kdy bude niva verze na repositari? A kde?

### ISSUE THREAD

**Issue by beatlecz** [JKubovy/plugin.video.tipsport.elh#16]
Diky

**Comment by JKubovy** [comment]
Nemám to vysledované a nikdy jsem nezjišťoval, jak často se natahují nové verze do repozitáře. Předpokládám, že to 24h to bude určitě. Pokud chceš novou verzi hned, tak si můžeš stáhnout *.zip a nainstalovat ručně.
Pro leiu (Kodi18) a starší verze: https://github.com/JKubovy/plugin.video.tipsport.elh/archive/refs/heads/leia.zip
Pro matrix (Kodi19+): https://github.com/JKubovy/plugin.video.tipsport.elh/archive/refs/heads/master.zip
