### ISSUE TITLE
Chyba při přihlášení

### ISSUE THREAD

**Issue by mara36** [JKubovy/plugin.video.tipsport.elh#17]
Ahoj, od minulého týdne se mi nedaří přihlásit (s verzí v0.8.10). Zkoušel jsem jak v KODI tak napřímo v pythonu - končí stejnou chybou (resources.lib.tipsport_exceptions.LoginFailedException: Login failed. Check username/password). Nedošlo ze strany tipsport.cz opět k úpravě loginu (neb přes web se úspěšně přihlásím)?

**Comment by JKubovy** [comment]
Ahoj, problémem je nový způsob přihlášení, který zavedl Tipsport.cz (slovenská mutace zatím funguje) a ještě se mi nepodařilo najít způsob, jak doplněk opravit. Diskuze ohledně tohoto problému se vedla/vede na fóru [xbmc-kodi.cz](https://www.xbmc-kodi.cz/prispevek-doplnek-tipsport-elh?pid=107619#pid107619).

**Comment by JKubovy** [comment]
Nová verze (0.8.12) by měla problém s přihlášením odstranit.

**Comment by mara36** [comment]
Ahoj,
děkuji za info a za rychlý fix. Právě jsem stáhl v0.8.12 a potvrzuji, že je funkční :-)
Dík.

**Comment by beatlecz** [comment]
Zase to nejede. Nebylo by nejlepší se s Tipsportem rovnou nějak domluvit? Přes ten jejich pošahaný web se to seká stejně. Přes Kodi to jede o dost líp. Ale asi jim jde o to aby měli na webu návštěvnost předpokládám :-(

**Comment by JKubovy** [comment]
Když jsem jim jednou psal s upozorněním na chybu, tak se mi ani neozvali.
