### ISSUE TITLE
Login fail again :(

### ISSUE THREAD

**Issue by beatlecz** [JKubovy/plugin.video.tipsport.elh#18]
Unfortunatelly login fails again :(

**Comment by beatlecz** [comment]
Asi se to nepodařilo spravit že? :(

**Comment by JKubovy** [comment]
Pokud se mi to povede opravit, tak vyjde nová verze pro všechny. Bohužel jsem se zatím nehnul z místa.

**Comment by SanduQi** [comment]
Bohuzel, taky se pridavam. Snad se to povede. Diky

**Comment by JKubovy** [comment]
Nová verze 0.8.13 by měla přihlašování opravit

**Comment by beatlecz** [comment]
Jsi frajer! Díky
