### ISSUE TITLE
Still can't login to tipsport.sk with 0.8.13 and 0.8.14

### ISSUE THREAD

**Issue by pvagner** [JKubovy/plugin.video.tipsport.elh#19]
Ahoj,
Stále sa zobrazuje notifikácia, že nie je možné prihlásiť. V logu sa nezobrazuje žiadna chyba, pretože exception je riadne odchytená. Nedokážem si poradiť ako získať ďalšie podrobnosti potrebné pre riešenie. Je možné, že na slovenskom webe sú iné post headers?

**Comment by JKubovy** [comment]
Je možné, že tipsport.sk používá jiné hlavičky. Kouknu na to, jestli se mi nepovede najít problém.

**Comment by JKubovy** [comment]
V nové verzi 0.8.15 by snad mělo být přihlašování pro sk mutaci opravené. Nemohu vyzkoušet, protože nemám sk účet, ale potenciální chybu jsem našel. Napiš, jestli to funguje a já pak ticket uzavřu.

**Comment by pvagner** [comment]
Ahoj,
Ďakujem, perfekt, 0.8.15 sa prihlasuje, funguje a môžem prehrávať videá.
