### ISSUE TITLE
Fotbal a další sporty

### ISSUE THREAD

**Issue by jagrs** [JKubovy/plugin.video.tipsport.elh#2]
A nemáš v plánu i další streamy z tipsportu,  třeba fotbal..?

**Comment by JKubovy** [comment]
Možná, že se k tomu někdy dostanu, ale teď se soustředím na hokej. Obecně je na [Tipsport.cz TV](https://www.tipsport.cz/tv) hodně typů streamu a ještě ne všechny se mi povedlo zprovoznit, takže nevím, jestli to vůbec půjde.

**Comment by JKubovy** [comment]
Konkrétně u fotbalu jsem narazil na nějaké streamy, které se mi nedaří v Kodi spustit. Pokud budu mít v budoucnu čas, podívám se na to podrobněji, ale prozatím zůstanu jenom u hokeje. Kdyby měl někdo zájem může udělat fork addonu a začít stavět na něm. Může napsat a já bych mu popsal v čem je problém.

**Comment by shrap42** [comment]
Mně by zajimaly ty duvody, proc to nejde/nechce se ti do toho. Tak jestli to muzes sdelit (at uz tady verejne nebo nejak soukrome). Jsem kdyztak na G+ jako David Zita, dik.

**Comment by JKubovy** [comment]
Důvodem, proč nejdou všechny streamy je knihovna, která se stará o přehrávání RTMP streamu v KODI. Jestli se něco nezměnilo, tak aktuální verze neumožňuje přehrání streamu, který používá [AMF3](https://en.wikipedia.org/wiki/Action_Message_Format). Snažil jsem se přijít na nějaké řešení v rámci projektu [inputsteam.rtmp](https://github.com/notspiff/inputstream.rtmp), ale marně. Pokud by se někomu podařilo zprovoznit zmíněné streamy, tak by se daly dodělat i další přenosy.
