### ISSUE TITLE
Stream ještě nebyl spuštěn..

### ISSUE THREAD

**Issue by jagrs** [JKubovy/plugin.video.tipsport.elh#3]
Dnes jsem to zapl na třetí třetinu třinec-liberec a píše to stream ještě nebyl spuštěn..

**Comment by JKubovy** [comment]
A jakou máš verzi? Nejnovější (v0.2.0) by měla fungovat v pořádku.

**Comment by jagrs** [comment]
Starou verzi....Ta nová je ok. Díky
