### ISSUE TITLE
Přidání hokejové 1. ligy

### ISSUE THREAD

**Issue by czkarelattl** [JKubovy/plugin.video.tipsport.elh#6]
Zdravím Honzo, myslíte, že by byl problém přidat českou hokejovou první ligu? V datech Tipsportu je jako "Česká Chance liga" ("competition": "Česká Chance liga")- ta volání rest api jsem si rozebral podle Vašeho kódu :) Zkoušel jsem si to naslepo přidat do konstanty COMPETITIONS v tipsport_stream_generator.py , ale po prostém zabalení zpět do zipu se mi addon nenainstaluje s tím, že je chybná struktura a nějak nemám čas to řešit víc.. :) Měl jsem to jako zip->v něm adresář plugin.video.tipsport.elh->a pak v něm stejné soubory jako tady na Githubu... Ale nic. Nikdy jsem se s addony pro Kodi nepotýkal, takže neznám ten ekosystém :) Díky :)
![image](https://user-images.githubusercontent.com/15997186/51111857-cc1b0b80-17fd-11e9-8ab0-25c53029df76.png)

**Comment by czkarelattl** [comment]
Ok, tak už se mi to povedlo vyřešit.. 
[plugin.video.tipsport.elh.zip](https://github.com/JKubovy/plugin.video.tipsport.elh/files/2756292/plugin.video.tipsport.elh.zip)

**Comment by JKubovy** [comment]
V případě, že se ti povedlo přidat celou ligu (s logem, překlady názvu týmů, atd.) tak můžeš přidat Pull requests, já se na to podívám a případně přidám do hlavní větve. Na druhou stranu se mi nechce kód měnit, jestliže by to fungovalo jenom částečně.

**Comment by JKubovy** [comment]
Upravil jsem addon, aby šla spustit i Chance Liga. Ještě potřebuji otestoval funkčnost a v případě, že se neobjeví problém doplněk aktualizuji.

**Comment by czkarelattl** [comment]
Ahoj, ok, super :) V pondělí jsem to zkoušel já i kamarád, oběma to
fungovalo, všechny zápasy. Jediné, co jsem teda neupravoval, jsou názvy
týmů. Plus co mi trochu vadilo je to, že se do popisu streamu tahá aktuální
skóre a čas, ale k tomu, aby se to obnovilo musím o úroveň výš a pak zase
zpátky.

*Karel Attl*


st 16. 1. 2019 v 12:51 odesílatel Jan Kubovy <notifications@github.com>
napsal:
